# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

augment_loop <- function(x, n, buff) {
    .Call('_SensitivityFunctions_augment_loop', PACKAGE = 'SensitivityFunctions', x, n, buff)
}

cholcpp <- function(x) {
    .Call('_SensitivityFunctions_cholcpp', PACKAGE = 'SensitivityFunctions', x)
}

matprod <- function(x) {
    .Call('_SensitivityFunctions_matprod', PACKAGE = 'SensitivityFunctions', x)
}

runifcpp <- function(lower, upper) {
    .Call('_SensitivityFunctions_runifcpp', PACKAGE = 'SensitivityFunctions', lower, upper)
}

subset <- function(x, row, column_min, column_max) {
    .Call('_SensitivityFunctions_subset', PACKAGE = 'SensitivityFunctions', x, row, column_min, column_max)
}

vecmult <- function(x, y) {
    .Call('_SensitivityFunctions_vecmult', PACKAGE = 'SensitivityFunctions', x, y)
}

